<?php
/**
 * Tweakwise & Emico (https://www.tweakwise.com/ & https://www.emico.nl/) - All Rights Reserved
 *
 * @copyright Copyright (c) 2017-2017 Tweakwise.com B.V. (https://www.tweakwise.com)
 * @license   Proprietary and confidential, Unauthorized copying of this file, via any medium is strictly prohibited
 */

namespace Emico\Tweakwise\Block\Autocomplete;

use Emico\Tweakwise\Model\Config;
use Magento\Framework\View\Element\Template;
use Magento\Framework\View\Element\Template\Context;

class FormMini extends Template
{
    /**
     * @var Config
     */
    protected $config;

    /**
     * FormMini constructor.
     * @param Config $config
     * @param Context $context
     * @param array $data
     */
    public function __construct(Config $config, Context $context, array $data = [])
    {
        parent::__construct($context, $data);

        $this->config = $config;
    }

    /**
     * {@inheritdoc}
     */
    public function _toHtml()
    {
        if (!$this->config->isAutocompleteEnabled()) {
            return '';
        }
        return parent::_toHtml(); // TODO: Change the autogenerated stub
    }
}