<?php
/**
 * Tweakwise & Emico (https://www.tweakwise.com/ & https://www.emico.nl/) - All Rights Reserved
 *
 * @copyright Copyright (c) 2017-2017 Tweakwise.com B.V. (https://www.tweakwise.com)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
use Emico\Tweakwise\Block\LayeredNavigation\RenderLayered\TreeRenderer\ItemRenderer;

/** @var $block ItemRenderer */
$item = $block->getItem();
?>
<li class="item">
    <a href="<?=$block->escapeUrl($item->getUrl())?>">
        <?=$block->getItemPrefix()?>
        <?=$block->escapeHtml($item->getLabel())?>
        <?=$block->getItemPostfix()?>

        <?php if ($block->shouldDisplayProductCountOnLayer()): ?>
            <span class="count">
                <?=htmlentities($item->getCount())?>
                <span class="filter-count-label">
                    <?php if ($item->getCount() == 1):?>
                        <?=__('item')?>
                    <?php else:?>
                        <?=__('items')?>
                    <?php endif;?>
                </span>
            </span>
        <?php endif; ?>
    </a>

    <?php if ($block->hasChildren()): ?>
        <ol class="items child-items">
            <?php foreach ($item->getChildren() as $child): ?>
                <?=$block->renderTreeItem($child)?>
            <?php endforeach; ?>
        </ol>
    <?php endif; ?>
</li>
