<?php
/**
 * Tweakwise & Emico (https://www.tweakwise.com/ & https://www.emico.nl/) - All Rights Reserved
 *
 * @copyright Copyright (c) 2017-2017 Tweakwise.com B.V. (https://www.tweakwise.com)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

use Emico\Tweakwise\Model\Catalog\Layer\Filter;

/** @var $block \Magento\LayeredNavigation\Block\Navigation */

if (!$block->canShowBlock()) return;
?>

<?php $filters = $block->getFilters(); /** @var $filters Filter[] */ ?>
<?php $useFormFilters = $block->getData('form_filters'); ?>
<?php $hasFilters = count($filters) > 0; ?>
<div class="block filter<?=($hasFilters ? ' filter-no-options' : '')?>"
     id="layered-filter-block"
     data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": false, "collateral": { "openedState": "filter-active", "element": "body" } }}'>
    <?php $filtered = count($block->getLayer()->getState()->getFilters()) ?>
    <div class="block-title filter-title" data-count="<?=$filtered?>">
        <strong data-role="title"><?=__('Shop By')?></strong>
    </div>
    <div class="block-content filter-content">
        <?=$block->getChildHtml('state')?>

        <?php if ($block->getLayer()->getState()->getFilters()): ?>
            <div class="block-actions filter-actions">
                <a href="<?=$block->getClearUrl() ?>" class="action clear filter-clear"><span><?=__('Clear All')?></span></a>
            </div>
        <?php endif; ?>

        <?php if ($filters): ?>
            <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?=__('Shopping Options') ?></strong>
            <div class="filter-options" id="narrow-by-list" data-role="content">
                <?php if ($useFormFilters): ?>
                    <form id="facet-filter-form" data-mage-init='{"tweakwiseNavigationForm": {"formFilters": "<?= $useFormFilters ?>"}}'>
                <?php endif;?>
                <?php foreach ($filters as $filter): ?>
                    <?php if ($filter->isCollapsible()): ?>
                        <?php $filterActive = $filter->isDefaultCollapsed() ? 'false' : '[0]'; ?>
                        <div class="collapsible-container <?=$filter->getCssClass()?>" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": <?=$filterActive?>}}'>
                            <?php $filterContentStyle = $filter->isDefaultCollapsed() ? ' style="display: none;"' : ''?>
                            <div data-role="collapsible" class="filter-options-item">
                                <div data-role="title" class="filter-options-title">
                                    <?=__($filter->getName())?>

                                    <?php $tooltip = $filter->getTooltip(); ?>
                                    <?php if ($tooltip): ?>
                                        <?php $tooltip = htmlentities($tooltip); ?>
                                        <span class="tooltip" data-tooltip="<?=$tooltip?>">I</span>
                                    <?php endif; ?>
                                </div>
                                <div data-role="content" class="filter-options-content"<?=$filterContentStyle?>>
                                    <?=$block->getChildBlock('renderer')->render($filter) ?>
                                </div>
                            </div>
                        </div>
                    <?php else: ?>
                        <div class="filter-options-item">
                            <div class="filter-options-title filter-options-title-non-collapsible"><?=__($filter->getName())?></div>
                            <div class="filter-options-content">
                                <?=$block->getChildBlock('renderer')->render($filter) ?>
                            </div>
                        </div>
                    <?php endif; ?>
                    <?php if ($useFormFilters): ?>
                        <li class="show-items-link">
                            <button type="submit" class="btn btn-primary btn-block js-btn-filter"><?=__(sprintf('Show <span>%s</span> items', $this->getLayer()->getProductCount())); ?></button>
                        </li>
                    <?php endif;?>
                <?php endforeach; ?>
                <?php if ($useFormFilters): ?>
                    </form>
                <?php endif;?>
            </div>
        <?php endif; ?>
    </div>
</div>