<?php
/**
 * Tweakwise & Emico (https://www.tweakwise.com/ & https://www.emico.nl/) - All Rights Reserved
 *
 * @copyright Copyright (c) 2017-2017 Tweakwise.com B.V. (https://www.tweakwise.com)
 * @license   Proprietary and confidential, Unauthorized copying of this file, via any medium is strictly prohibited
 */
use Emico\Tweakwise\Block\LayeredNavigation\RenderLayered\CheckboxRenderer;

/** @var $block CheckboxRenderer */
?>
<ol class="items">
    <?php foreach ($block->getItems() as $item): ?>
        <li class="item">
            <a href="<?=$block->escapeUrl($item->getUrl())?>">
                <input id="inputCheckbox<?=$this->getItemId($item)?>" type="checkbox" <?=($item->isSelected() ? 'checked="checked"' : '')?>>

                <label for="inputCheckbox<?=$this->getItemId($item)?>"><?=$item->getLabel()?></label>
                <?php if ($this->shouldDisplayProductCountOnLayer()): ?>
                    <span class="count">
                        <?=$item->getCount()?>
                        <span class="filter-count-label">
                            <?php if ($item->getCount() == 1):?>
                                <?=__('item')?>
                            <?php else:?>
                                <?=__('items')?>
                            <?php endif;?>
                        </span>
                    </span>
                <?php endif; ?>
            </a>
        </li>
    <?php endforeach; ?>
</ol>