<?php
/**
 * Tweakwise & Emico (https://www.tweakwise.com/ & https://www.emico.nl/) - All Rights Reserved
 *
 * @copyright Copyright (c) 2017-2017 Tweakwise.com B.V. (https://www.tweakwise.com)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
use Emico\Tweakwise\Block\LayeredNavigation\RenderLayered\DefaultRenderer;

/** @var $block DefaultRenderer */
?>
<div data-mage-init='{"tweakwiseNavigationFilter": {}}'>
    <ol class="items">
        <?php foreach ($block->getItems() as $item): ?>
            <li class="item<?=$block->itemDefaultHidden($item) ? ' default-hidden' : ''?>">
                <a href="<?=$block->escapeUrl($item->getUrl())?>">
                    <?php if ($block->showCheckbox()): ?>
                        <input id="inputCheckbox<?=$block->getCssItemId($item)?>" type="checkbox" <?=($item->isSelected() ? 'checked="checked"' : '')?>>

                        <label for="inputCheckbox<?=$block->getCssItemId($item)?>">
                            <?=$block->escapeHtml($block->getItemPrefix())?>
                            <?=$block->escapeHtml($item->getLabel())?>
                            <?=$block->escapeHtml($block->getItemPostfix())?>
                        </label>
                    <?php else: ?>
                        <?=$block->escapeHtml($block->getItemPrefix())?>
                        <?=$block->escapeHtml($item->getLabel())?>
                        <?=$block->escapeHtml($block->getItemPostfix())?>
                    <?php endif; ?>

                    <?php if ($block->shouldDisplayProductCountOnLayer()): ?>
                        <span class="count">
                            <?=$block->escapeHtml($item->getCount())?>
                            <span class="filter-count-label">
                                <?php if ($item->getCount() == 1):?>
                                    <?=__('item')?>
                                <?php else:?>
                                    <?=__('items')?>
                                <?php endif;?>
                            </span>
                        </span>
                    <?php endif; ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ol>

    <?php if ($block->hasHiddenItems()): ?>
        <a class="more-items"><?=$block->escapeHtml(__($block->getMoreItemText()))?></a>
        <a class="less-items default-hidden"><?=$block->escapeHtml(__($block->getLessItemText()))?></a>
    <?php endif; ?>
</div>