<?php
/**
 * Tweakwise & Emico (https://www.tweakwise.com/ & https://www.emico.nl/) - All Rights Reserved
 *
 * @copyright Copyright (c) 2017-2017 Tweakwise.com B.V. (https://www.tweakwise.com)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
use Emico\Tweakwise\Block\LayeredNavigation\RenderLayered\DefaultRenderer;

/** @var $block DefaultRenderer */
?>
<div data-mage-init='<?=$block->getJsNavigationConfig()?>'>
    <ol class="items">
        <?php foreach ($block->getItems() as $item): ?>
            <li class="item<?=$block->itemDefaultHidden($item) ? ' default-hidden' : ''?>">
                <?=$block->renderAnchorHtmlTag($item);?>
                    <?php if ($block->showCheckbox()): ?>
                        <input id="inputCheckbox<?=$block->getCssItemId($item)?>"
                               name="<?=$item->getFilter()->getFacet()->getFacetSettings()->getUrlKey()?>[]"
                               type="checkbox" <?=($item->isSelected() ? 'checked="checked"' : '')?>
                               value="<?=$block->escapeHtmlAttr($item->getAttribute()->getTitle())?>"
                        >

                        <label for="inputCheckbox<?=$block->getCssItemId($item)?>">
                            <?=$block->getItemPrefix()?>
                            <?=$item->getLabel()?>
                            <?=$block->getItemPostfix()?>
                        </label>
                    <?php else: ?>
                        <?=$block->getItemPrefix()?>
                        <?=$item->getLabel()?>
                        <?=$block->getItemPostfix()?>
                    <?php endif; ?>

                    <?php if ($block->shouldDisplayProductCountOnLayer()): ?>
                        <span class="count">
                            <?=htmlentities($item->getCount())?>
                            <span class="filter-count-label">
                                <?php if ($item->getCount() == 1):?>
                                    <?=__('item')?>
                                <?php else:?>
                                    <?=__('items')?>
                                <?php endif;?>
                            </span>
                        </span>
                    <?php endif; ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ol>

    <?php if ($block->hasHiddenItems()): ?>
        <a class="more-items"><?=__($block->getMoreItemText())?></a>
        <a class="less-items default-hidden"><?=__($block->getLessItemText())?></a>
    <?php endif; ?>
</div>