<?php
/**
 * Tweakwise & Emico (https://www.tweakwise.com/ & https://www.emico.nl/) - All Rights Reserved
 *
 * @copyright Copyright (c) 2017-2017 Tweakwise.com B.V. (https://www.tweakwise.com)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
use Emico\Tweakwise\Block\LayeredNavigation\RenderLayered\SliderRenderer;

/** @var $block SliderRenderer */
?>
<div class="slider-attribute" id="attribute-slider-<?=$block->getCssId()?>">
    <div class="labels">
        <span class="min-value">
            <span class="prefix"><?=$block->getItemPrefix()?></span>
            <?=$block->renderValue($block->getMinValue())?>
            <span class="postfix"><?=$block->getItemPostfix()?></span>
        </span>
        <span class="max-value">
            <span class="prefix"><?=$block->getItemPrefix()?></span>
            <?=$block->renderValue($block->getMaxValue())?>
            <span class="postfix"><?=$block->getItemPostfix()?></span>
        </span>
    </div>
    <div class="slider" data-mage-init='<?=$block->getJsSliderConfig()?>'></div>
    <div class="labels">
        <span class="current-min-value">
            <span class="prefix"><?=$block->getItemPrefix()?></span>
            <?=$block->renderValue($block->getCurrentMinValue())?>
            <span class="postfix"><?=$block->getItemPostfix()?></span>
        </span>
        <span class="current-max-value">
            <span class="prefix"><?=$block->getItemPrefix()?></span>
            <?=$block->renderValue($block->getCurrentMaxValue())?>
            <span class="postfix"><?=$block->getItemPostfix()?></span>
        </span>
    </div>
    <div class="slider-inputs">
        <label for="<?=$block->getUrlKey()?>-min"><?=__('From')?></label>
        <input type="text"
               class="slider-min js-skip-submit"
               id="<?=$block->getUrlKey()?>-min"
               name="<?=$block->getUrlKey()?>-min"
               value="<?=$block->getCurrentMinValue()?>"
        >
        <label for="<?= $block->getUrlKey()?>-max"><?=__('To')?></label>
        <input type="text"
               class="slider-max js-skip-submit"
               id="<?= $block->getUrlKey() ?>-max"
               name="<?=$block->getUrlKey() ?>-max"
               value="<?= $block->getCurrentMaxValue() ?>"
        >
        <input type="hidden"
               class="slider-url-value"
               name="<?=$block->getUrlKey()?>"
               value="<?=sprintf('%s-%s', $block->getCurrentMinValue(), $block->getCurrentMaxValue())?>"
        >
    </div>
</div>
