<?php
/**
 * Tweakwise & Emico (https://www.tweakwise.com/ & https://www.emico.nl/) - All Rights Reserved
 *
 * @copyright Copyright (c) 2017-2017 Tweakwise.com B.V. (https://www.tweakwise.com)
 * @license   Proprietary and confidential, Unauthorized copying of this file, via any medium is strictly prohibited
 */
use Emico\Tweakwise\Block\LayeredNavigation\RenderLayered\TreeRenderer;

/** @var $block TreeRenderer */
?>
<ol class="items">
    <?php foreach ($block->getItems() as $item): ?>
        <?=$block->renderTreeItem($item)?>
    <?php endforeach; ?>
</ol>